version: 2
jobs:

  test-unit:
    docker:
      - image: circleci/python:2.7
    steps:
      - attach_workspace:
          at: ~/ws
      - checkout:
          path:
            "bxcommon"
      - restore_cache: # restores saved dependency cache if the Branch key template or requirements.txt files have not changed since the previous run
          key: deps1-{{ .Branch }}-{{ checksum "bxcommon/requirements.txt" }}
      - run: # install and activate virtual environment with pip
          command: |
            python -m virtualenv venv
            . venv/bin/activate
            pip install -r bxcommon/requirements.txt
      - save_cache: # special step to save dependency cache
          key: deps1-{{ .Branch }}-{{ checksum "bxcommon/requirements.txt" }}
          paths:
            - "venv"
      - persist_to_workspace:
          root: .
          paths:
            - venv
      - run: # run tests
          name: Tests
          command: |
            . venv/bin/activate
            cd bxcommon/test/
            PYTHONPATH=../../bxcommon/src/ \
            PYLINTRC_PATH=../../bxcommon/pylintrc \
            python -m unittest discover --verbose
      - store_artifacts:
          path: test-reports/
          destination: tr1

  build:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/ws

    steps:
      - checkout
      - attach_workspace:
          at: ~/ws
      - run:
          name: Package
          command: 'echo "Yay build!"'

  deploy:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/ws

    steps:
      - checkout
      - attach_workspace:
          at: ~/ws
      - run:
          name: Package
          command: 'echo "Yay deploy!"'

workflows:
  version: 2

  test-build:
    jobs:
      - test-unit
      - build:
          requires:
            - test-unit
          filters:
            branches:
              only: develop

      - deploy:
          filters:
            branches:
              only: develop
          requires:
            - build
