version: 2
jobs:

  test-unit:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/common
    steps:
      - checkout
      - attach_workspace:
          at: ~/common
      - restore_cache: # restores saved dependency cache if the Branch key template or requirements.txt files have not changed since the previous run
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run: # install and activate virtual environment with pip
          command: |
            python -m virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache: # special step to save dependency cache
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run: # run tests
          name: Tests
          command: |
            . venv/bin/activate
            python -m unittest discover test
      - store_artifacts: # special step to store test reports as artifacts
          path: test-reports/
          destination: tr1

  build:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/common

    steps:
      - checkout
      - attach_workspace:
          at: ~/common
      - run:
          name: Package
          command: 'echo "Yay develop build!"'

  build-prod:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/common

    steps:
      - checkout
      - attach_workspace:
          at: ~/common
      - run:
          name: Package
          command: 'echo "Yay master build!"'

workflows:
  version: 2

  test-build:
    jobs:
      - test-unit
      - build:
          requires:
            - test-unit
          filters:
            branches:
              only: develop

      - build-prod:
          requires:
            - test-unit
          filters:
            branches:
              only: master
