version: 2
jobs:

  test:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/ws
    steps:
      - attach_workspace:
          at: ~/ws
      - checkout:
          path:
            "bxcommon"
      - restore_cache: # restores saved dependency cache if the Branch key template or requirements.txt files have not changed since the previous run
          key: deps1-{{ .Branch }}-{{ checksum "bxcommon/requirements.txt" }}
      - run: # install and activate virtual environment with pip
          command: |
            python -m virtualenv venv
            . venv/bin/activate
            pip install -r bxcommon/requirements.txt
      - save_cache: # special step to save dependency cache
          key: deps1-{{ .Branch }}-{{ checksum "bxcommon/requirements.txt" }}
          paths:
            - "venv"
      - persist_to_workspace:
          root: .
          paths:
            - venv
      - run:
          name: Unit Tests
          command: |
            . venv/bin/activate
            cd bxcommon/test/unit
            PYTHONPATH=../../../bxcommon/src/ \
            python -m unittest discover --verbose
      - run: # check coverage
          name: Check Coverage
          command: |
            . venv/bin/activate
            cd bxcommon/test/unit
            PYTHONPATH=../../../bxcommon/src/ \
            coverage run --source=../../src -m unittest discover && coverage report --fail-under=01
      - run:
          name: Integration Tests
          command: |
            . venv/bin/activate
            cd bxcommon/test/integration
            PYTHONPATH=../../../bxcommon/src/ \
            python -m unittest discover --verbose
      - run: # run pylint
          name: Lint Score
          command: |
            . venv/bin/activate
            cd bxcommon
            # The || exit 0 bypasses not failing the build for <10 score
            pylint src/bxcommon --msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}" --rcfile=pylintrc || exit 0
      - store_artifacts:
          path: test-reports/
          destination: tr1

  build:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/ws

    steps:
      - checkout
      - attach_workspace:
          at: ~/ws
      - run:
          name: Package
          command: 'echo "Yay build!"'

  deploy:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/ws

    steps:
      - checkout
      - attach_workspace:
          at: ~/ws
      - run:
          name: Package
          command: 'echo "Yay deploy!"'

workflows:
  version: 2

  test-build:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: develop

      - deploy:
          filters:
            branches:
              only: develop
          requires:
            - build
